services:
  db:
    image: postgres:15-alpine
    container_name: ghn_postgres_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github_notifier_api
    restart: always
    env_file:
      - .env
    environment:
      DB_HOST: db
    depends_on:
      db:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      
      - "traefik.http.routers.ghnotifier.rule=Host(`gh-notifier.online`)"
      - "traefik.http.routers.ghnotifier.entrypoints=websecure"
      - "traefik.http.routers.ghnotifier.tls=true"
      - "traefik.http.routers.ghnotifier.tls.certresolver=myresolver"

      - "traefik.http.services.ghnotifier.loadbalancer.server.port=8080"
    networks:
      - default
      - traefik-public

volumes:
  postgres_data:

networks:
  traefik-public:
    external: true