// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Oleksandr",
            "email": "[EMAIL_ADDRESS]"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/confirm": {
            "get": {
                "description": "Confirms a subscription using a token.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Confirm subscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/subscription.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/subscription.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/subscribe": {
            "post": {
                "description": "Subscribes a user to receive email notifications for new commits in a specific GitHub repository.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Subscribe to repository updates",
                "parameters": [
                    {
                        "description": "Subscription request",
                        "name": "SubscribeRequest",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/subscription.SubscribeRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/subscription.SubscribeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/subscription.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/subscription.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/subscriptions": {
            "get": {
                "description": "Retrieves all subscriptions for a given email address.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Get all subscriptions for an email",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Email address",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/subscription.SubscriptionDTO"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/subscription.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/subscription.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/api/unsubscribe": {
            "get": {
                "description": "Unsubscribes a user from receiving email notifications for a specific repository.",
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "subscription"
                ],
                "summary": "Unsubscribe from repository updates",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Subscription token",
                        "name": "token",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/subscription.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/subscription.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "subscription.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "subscription.SubscribeRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                }
            }
        },
        "subscription.SubscribeResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "subscription.SubscriptionDTO": {
            "type": "object",
            "properties": {
                "is_confirmed": {
                    "type": "boolean"
                },
                "last_checked": {
                    "type": "string"
                },
                "last_tag": {
                    "type": "string"
                },
                "repo_path": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "GitHub Notifier API",
	Description:      "GitHub Notifier is a service that monitors GitHub repositories and sends email notifications when new commits are pushed to the repositories.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
