name: CD Pipeline - Deploy to VPC

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: SSH and Deploy to VPC
        uses: appleboy/ssh-action@v1.0.3
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: 22
          envs: ENV_FILE
          script: |
            set -e

            cd /opt

            if [ ! -d "GitHub-Notifier" ]; then
              echo "Cloning repository..."
              git clone https://github.com/KovalovOL/GitHub-Notifier.git
              cd GitHub-Notifier
            else
              echo "Repository exists. Pulling latest changes..."
              cd GitHub-Notifier
              git pull origin main
            fi

            # Create/Overwrite .env from the GitHub Secret
            echo "Creating .env file..."
            echo "$ENV_FILE" > .env

            echo "Rebuilding and deploying containers..."
            docker compose up -d --build

